## Quiz
* 이론 : 1번 ~ 18번
* 실습 : 19번 ~ 25번

In [100]:
# Quiz 19번) Numpy 를 사용하여 주어진 배열의 홀수와 짝수를 분리하는 프로그램을 작성
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

odd=arr[arr % 2 != 0]      # 홀수
even=arr[arr % 2 == 0]     # 짝수

print("홀수 배열:", odd)
print("짝수 배열:", even)

홀수 배열: [1 3 5 7 9]
짝수 배열: [ 2  4  6  8 10]


In [101]:
# Quiz 20번) 다음과 같은 두 행렬의 합을 계산하는 Numpy 프로그램을 작성하세요.
a=np.array([[1, 2],
            [3, 4]])

b=np.array([[5, 6],
            [7, 8]])

result=a + b
print("두 행렬의 합: \n", result)

두 행렬의 합: 
 [[ 6  8]
 [10 12]]


In [103]:
# Quiz 21번)  21. 다음과 같은 2차원 배열이 주어졌을 때, 각 열(column)의 평균을 구하는 Numpy 프로그램을 작성하세요.
data=np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]])

column_means=np.mean(data, axis=0)       # 각 열의 평균 계산
print("각 열의 평균:", column_means)

각 열의 평균: [5.5 6.5 7.5]


In [104]:
# Quiz 22번) 다음과 같은 1차원 배열이 주어졌을 때, 배열의 중앙값(median)을 계산하는 Numpy 프로그램을 작성하세요. (배열 : [3, 1, 8, 4, 2, 5, 7, 6])
arr=np.array([3, 1, 8, 4, 2, 5, 7, 6])

median_value=np.median(arr)                   # 배열의 중앙값 계산
print("배열의 중앙값:", median_value)

배열의 중앙값: 4.5


In [105]:
# Quiz 23번) 다음과 같은 2차원 배열이 주어졌을 때, 각 행(row)의 최솟값을 찾는 Numpy 프로그램을 작성하세요.
arr=np.array([[5, 12, 7],
              [9, 3, 20],
              [8, 15, 11],
              [6, 10, 4]])

minimum_values=np.min(arr, axis=1)   # 각 행의 최솟값 계산
print("각 행의 최솟값:", minimum_values)

각 행의 최솟값: [5 3 8 4]


In [106]:
# Quiz 24번) Numpy 함수를 활용하여 3x3 크기의 다음과 같은 배열을 생성하세요. 
#            arange(), reshape() 함수 사용

arr=np.arange(1, 10).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [107]:
# Quiz 25번) Numpy 함수를 사용하여 5x5 크기의 다음과 같은 배열을 생성하세요. zeros(), 슬라이싱 활용
arr=np.zeros((5, 5), dtype=int)

arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
print(arr)

[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
